import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "../components/Header/Header";
import Hero from "../components/Hero/Hero";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const navigation = [
  { label: 'Product', href: '#' },
  { label: 'Features', href: '#' },
  { label: 'Marketplace', href: '#' },
  { label: 'Company', href: '#' },
]

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Header companyName="Vida Felina" companyLogo="/vida-felina-logo.jpg" navigationItems={navigation} />
        <Hero />
        {children}
      </body>
    </html>
  );
}
